Repository HackYourFuture-CPH/fp-class18, pull requests merged in 2021-11, with the labels that each got.

#26 Adding product images and hero image to assets/images folder
  src/client/assets/images/hero-image.png
  src/client/assets/images/image01.png
  src/client/assets/images/image02.png
  src/client/assets/images/image03.png
  src/client/assets/images/image04.png
  src/client/assets/images/image05.png
  src/client/assets/images/image06.png
  src/client/assets/images/image07.png
  src/client/assets/images/image08.png
  src/client/assets/images/image09.png
  src/client/assets/images/image10.png
  src/client/assets/images/image11.png
  src/client/assets/images/image12.png
Labels: Frontend

#23 Databases: Create Migrations for Users Table
  src/server/migrations/20211102015225_create_users_table.js
Labels: Databases

#31 Databases: Created Migrations for Categories Table
  src/server/migrations/20211103214847_categories.js
Labels: Databases

#34 Databases: migrate orders table
  src/server/migrations/20211104081529_orders.js
Labels: Databases

#38 Databases: Created Migrations for Products Table
  src/server/migrations/20211105095000_products-table.js
Labels: Databases

#28 Databases: Feature/order items table
  src/server/migrations/20211108150400_order_items.js
Labels: Databases

#22 Storybook: Footer Component
  src/client/components/Footer/Footer.component.js
  src/client/components/Footer/Footer.stories.js
  src/client/components/Footer/Footer.styles.css
Labels: storybook

#42 Databases: Add database migration for Favorites table
  src/server/migrations/20211107144056_favorites.js
Labels: Databases

#60 Storybook: Deployment
  package.json
Labels: storybook

#49 Deleted migration and seeding for modules
  src/server/migrations/20200510015322_create_modules_schema.js
  src/server/seeds/development/modules.js
Labels: Databases

#53 Databases: Create Seeding for Products and Categories Table
  src/server/seeds/development/products.js
Labels: Databases

#69 Storybook: add libary dependancy to use storybook-controls
  package-lock.json
  package.json
  src/client/.storybook/main.js
Labels: storybook

#66 Databases: Create Seeding for Products and Categories Table Separately
  src/server/seeds/development/01_categories.js
  src/server/seeds/development/02_products.js
Labels: Databases

#71 Frontend: dummy Pages Created
  src/client/containers/404Page/404Page.Container.js
  src/client/containers/404Page/404Page.Style.css
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/CartPage/CartPage.Style.css
  src/client/containers/CategoryPage/CategoryPage.Container.js
  src/client/containers/CategoryPage/CategoryPage.Style.css
  src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
  src/client/containers/ConfirmationPage/ConfirmationPage.Style.css
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/FavoritesPage/FavoritesPage.Style.css
  src/client/containers/LandingPage/LandingPage.Container.js
  src/client/containers/LandingPage/LandingPage.Style.css
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
  src/client/containers/OrderPage/OrderPage.Container.js
  src/client/containers/OrderPage/OrderPage.Style.css
  src/client/containers/ProductPage/ProductPage.Container.js
  src/client/containers/ProductPage/ProductPage.Style.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
  src/client/containers/ProfilePage/ProfilePage.Style.css
Labels: Frontend

#32 Storybook: Added NumberInput component
  src/client/components/NumberInput/NumberInput.component.js
  src/client/components/NumberInput/NumberInput.stories.js
  src/client/components/NumberInput/NumberInput.styles.css
Labels: storybook

#74 Storybook: Button Component
  src/client/components/Button/Button.component.js
  src/client/components/Button/Button.stories.js
  src/client/components/Button/Button.styles.css
Labels: storybook

#51 Backend: Endpoint to retrieve user info- GET api/users/{user_id}
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/users.router.js
Labels: Backend

#55 Storybook: Carousel for monthly and similar products
  src/client/components/Carousel/Carousel.component.js
  src/client/components/Carousel/Carousel.stories.js
  src/client/components/Carousel/Carousel.style.css
Labels: storybook

#27 Storybook: adding sorting components
  src/client/components/Sorting/Sorting.component.js
  src/client/components/Sorting/Sorting.stories.js
  src/client/components/Sorting/Sorting.styles.css
  src/client/components/Sorting/helper.js
Labels: storybook, Frontend

#84 Backend: Endpoint to retrieve categories info- GET api/categories
  src/server/api/controllers/categories.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/categories.router.js
Labels: Backend

#89 Backend: Endpoint to show monthly products - GET api/products?daysBeforeToday={number}
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#81 Storybook: Products Pagination
  src/client/components/ProductsPagination/ProductsPagination.component.js
  src/client/components/ProductsPagination/ProductsPagination.stories.js
  src/client/components/ProductsPagination/ProductsPagination.styles.css
Labels: storybook

#82 Storybook : Product Details Component
  src/client/components/ProductDetails/Heart.js
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/ProductDetails/ProductDetails.stories.js
  src/client/components/ProductDetails/ProductDetails.style.css
Labels: storybook

#29 Storybook: Menu Component
  src/client/assets/images/favorite-icon.png
  src/client/assets/images/shopping-cart.png
  src/client/assets/images/user-login.png
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.stories.js
  src/client/components/menu/Menu.styles.css
Labels: storybook

#106 Added styles to fit landing page
  src/client/components/ProductView/ProductView.styles.css
Labels: Frontend

#108 Databases: Create Migrations for Order_Items table
  src/server/migrations/20211118122009_order_items.js
Labels: Databases

#110 Databases: Created seeding for users table
  src/server/seeds/development/03_users.js
Labels: Databases

#114 Frontend : Menu Style Updated
  src/client/components/menu/Menu.styles.css
Labels: storybook

#112 Databases: Created seeding for orders table
  src/server/seeds/development/05_orders.js
Labels: Databases

#111 Databases: Created seeding for favorites table
  src/server/seeds/development/04_favorites.js
Labels: Databases

#113 Databases: Created seeding for order_items table
  src/server/seeds/development/06_order_items.js
Labels: Databases

#88 Backend: Endpoint to update delivery info for user - PUT api/users/{u…
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#96 Frontend: Landing Page
  README.md
  src/client/App.js
  src/client/containers/LandingPage/LandingPage.Container.js
  src/client/containers/LandingPage/LandingPage.Style.css
  src/client/hooks/UseFetchApi.js
Labels: Frontend

#120 Backend: Endpoint to store a new order for users : POST api/orders
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/orders.router.js
Labels: Backend

#125 Databases: Add Id For Products, Users and Orders Seed
  src/server/seeds/development/02_products.js
  src/server/seeds/development/03_users.js
  src/server/seeds/development/05_orders.js
Labels: Databases

#127 Databases: Updated seeds to avoid default values
  src/server/seeds/development/02_products.js
  src/server/seeds/development/03_users.js
  src/server/seeds/development/04_favorites.js
  src/server/seeds/development/05_orders.js
  src/server/seeds/development/06_order_items.js
Labels: Databases

#129 Frontend: Update Landing Page for Carousel
  src/client/containers/LandingPage/LandingPage.Container.js
Labels: Frontend

#132 Added seeds to Production
  src/server/seeds/production/01_categories.js
  src/server/seeds/production/02_products.js
  src/server/seeds/production/03_users.js
  src/server/seeds/production/04_favorites.js
  src/server/seeds/production/05_orders.js
  src/server/seeds/production/06_order_items.js
Labels: Databases

#128 Fixed issues on Carousel component(Images, CSS)
  src/client/components/Carousel/Carousel.component.js
  src/client/components/Carousel/Carousel.stories.js
  src/client/components/Carousel/Carousel.style.css
Labels: Frontend

#99 Frontend: Category Page
  src/client/App.js
  src/client/containers/CategoryPage/CategoryPage.Container.js
  src/client/containers/CategoryPage/CategoryPage.Style.css
Labels: Frontend

#87 Backend: Endpoint to save users - POST api/users
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#145 Backend: Small Fix about User Patch Swagger Name
  src/server/api/routes/users.router.js
Labels: Backend

#154 FrontEnd: 404Page
  src/client/App.js
  src/client/containers/404Page/404Page.Container.js
  src/client/containers/404Page/404Page.Style.css
Labels: Frontend

#155 FrontEnd: Change the category page calling in Menu
  src/client/components/menu/Menu.component.js
Labels: Frontend

#122 Backend: Endpoint to retrieve favorite products by user - GET api/users/{user_id}/favorites
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#139 Storybook: Content Card - TotalPrice
  src/client/components/TotalPriceCard/TotalPriceCard.component.js
  src/client/components/TotalPriceCard/TotalPriceCard.stories.js
  src/client/components/TotalPriceCard/TotalPriceCard.styles.css
Labels: storybook

#153 Frontend: Fixed productDetails component Image bug
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/ProductDetails/ProductDetails.stories.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: storybook, Frontend

#79 Storybook: Added contact form
  src/client/components/ContactForm/ContactForm.component.js
  src/client/components/ContactForm/ContactForm.stories.js
  src/client/components/ContactForm/ContactForm.styles.css
  src/client/containers/SignUp/index.js
  src/client/firebase/auth.js
Labels: storybook

#148 Frontend: Linking Product Image to Product page for Images in Carrou…
  src/client/components/Carousel/Carousel.component.js
  src/client/components/Carousel/Carousel.stories.js
  src/client/components/ProductView/ProductView.component.js
  src/client/components/ProductView/ProductView.stories.js
  src/client/containers/LandingPage/LandingPage.Container.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#146 Deployment: Procfile for automatic Database setup
  Procfile
Labels: Deployment

#159 Databases: Edit Seeding for Products Table, both development and production
  src/client/assets/images/image13.png
  src/client/assets/images/image14.png
  src/client/containers/404Page/404Page.Style.css
  src/server/migrations/20211108150400_order_items.js
  src/server/seeds/development/02_products.js
  src/server/seeds/production/02_products.js
Labels: Databases

#165 Deployment: fixing bug by changing name of order_items
  src/server/migrations/20211118122009_order_items.js
Labels: Deployment

#126 Storybook: Content Card - Purchases
  src/client/components/Purchases/Purchases.component.js
  src/client/components/Purchases/Purchases.stories.js
  src/client/components/Purchases/Purchases.styles.css
Labels: storybook

#135 Storybook: Shopping card Item
  src/client/components/ShoppingItem/ShoppingItem.js
  src/client/components/ShoppingItem/ShoppingItem.stories.js
  src/client/components/ShoppingItem/ShoppingItem.styles.css
  src/client/components/ShoppingItem/Trash.js
  src/client/components/ShoppingItem/heart.js
Labels: storybook

#52 Storybook: Added delivery info
  src/client/components/DeliveryInfo/DeliveryInfo.component.js
  src/client/components/DeliveryInfo/DeliveryInfo.stories.js
  src/client/components/DeliveryInfo/DeliveryInfo.styles.css
  src/client/firebase/auth.js
Labels: storybook

#167 FrontEnd: Category Page has to show Not Found Page when given category not available
  src/client/containers/CategoryPage/CategoryPage.Container.js
Labels: Frontend

#115 Backend: Endpoint to retrieve user-orders
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/orders.router.js
Labels: Backend

#166 FrontEnd: Product Page has to show Not Found Page when given product is not available
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#130 Storybook: Modal View Product Added Confirmation Component
  src/client/assets/images/addedCart.png
  src/client/components/Modal/Modal.component.js
  src/client/components/Modal/Modal.stories.js
  src/client/components/Modal/Modal.styles.css
Labels: storybook

#157 Frontend: Monthly Arrivals Page
  src/client/App.js
  src/client/components/menu/Menu.component.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
Labels: Frontend

#173 Fix on sorting component styling on Category Page
  src/client/containers/CategoryPage/CategoryPage.Container.js
  src/client/containers/CategoryPage/CategoryPage.Style.css
Labels: Frontend

#172 Deleted sample modules
  src/client/App.js
  src/client/components/SampleComponent/SampleComponent.js
  src/client/components/SampleComponent/SampleComponent.stories.js
  src/client/components/SampleComponent/SampleComponent.styles.css
  src/client/containers/Home/Home.js
  src/client/containers/Home/Home.test.js
  src/client/containers/Profile/index.js
  src/server/api/controllers/modules.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/modules.router.js
Labels: Frontend, Backend

#174 FrontEnd: fixed css bug on product details in MonthlyArrivals
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
Labels: Frontend

#149 Firebase: add Google account signin option to FirebaseContext
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.styles.css
  src/client/firebase/FirebaseContext.js
  src/client/firebase/auth.js
  src/client/firebase/configure.js
Labels: Firebase

#67 Backend: Endpoint to retrieve order info- GET api/orders/{:id}
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/orders.router.js
Labels: Backend

#188 Frontend:Monthly arrivals typo fix
  src/client/components/menu/Menu.component.js
Labels: Frontend
