Repository HackYourFuture-CPH/fp-class18, pull requests merged in 2021-12, with the labels that each got.

#178 Database: Changes to database setup to add user from firebase
  .env.example
  src/client/firebase/auth.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
  src/server/migrations/20211102015225_create_users_table.js
  src/server/migrations/20211104081529_orders.js
  src/server/migrations/20211107144056_favorites.js
  src/server/seeds/development/03_users.js
  src/server/seeds/development/04_favorites.js
  src/server/seeds/development/05_orders.js
Labels: Databases, Firebase

#195 Storybook: Edit ShoppingItem Component
  src/client/components/NumberInput/NumberInput.component.js
  src/client/components/ShoppingItem/ShoppingItem.js
  src/client/components/ShoppingItem/ShoppingItem.stories.js
  src/client/components/ShoppingItem/ShoppingItem.styles.css
  src/client/components/ShoppingItem/Trash.js
Labels: storybook

#204 FrontEnd: Loader Issue when rendering productpage and category page
  src/client/containers/CategoryPage/CategoryPage.Container.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#182 Frontend: shopping Cart Page
  src/client/App.js
  src/client/components/ContactForm/ContactForm.component.js
  src/client/components/ContactForm/ContactForm.styles.css
  src/client/components/DeliveryInfo/DeliveryInfo.component.js
  src/client/components/DeliveryInfo/DeliveryInfo.stories.js
  src/client/components/DeliveryInfo/DeliveryInfo.styles.css
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/CartPage/CartPage.Style.css
Labels: Frontend

#206 FrontEnd: AboutUs page and ContactUs page
  src/client/App.js
  src/client/assets/images/Phone_icon.png
  src/client/assets/images/aboutUs.png
  src/client/assets/images/aboutUs2.png
  src/client/assets/images/clock-icon.png
  src/client/assets/images/contactUs.png
  src/client/assets/images/email-icon.png
  src/client/assets/images/location-icon.png
  src/client/components/menu/Menu.component.js
  src/client/containers/AboutPage/AboutPage.Container.js
  src/client/containers/AboutPage/AboutPage.Style.css
  src/client/containers/ContactPage/ContactPage.Container.js
  src/client/containers/ContactPage/ContactPage.Style.css
Labels: Frontend

#194 Frontend: Improve Product Details for responsive
  src/client/components/NumberInput/NumberInput.styles.css
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/ProductDetails/ProductDetails.style.css
Labels: storybook, Frontend

#187 Backend: Improvement on POST api/orders
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/orders.router.js
  src/server/migrations/20211104081529_orders.js
Labels: Backend

#198 Backend: EndPoint to create favorites-POST api/users/{:id}/favorites/
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#199 Backend: EndPoint to eliminate favorites-DELETE api/users/{:id}/favorites
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: Backend

#215 Frontend: Update about product details
  src/client/components/ProductDetails/ProductDetails.style.css
Labels: Frontend

#213 Storybook/FrontEnd: Menu component Responsive with hamburger Menu
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.styles.css
Labels: Frontend

#140 Feature/order page
  src/client/App.js
  src/client/containers/OrderPage/OrderPage.Container.js
  src/client/containers/OrderPage/OrderPage.Style.css
Labels: Frontend

#152 Frontend: Favorites page
  src/client/App.js
  src/client/components/menu/Menu.component.js
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/FavoritesPage/FavoritesPage.Style.css
  src/server/api/routes/users.router.js
Labels: Frontend

#214 Link explore category button to category page
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#185 Frontend: Order Confirmation Page
  src/client/App.js
  src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
  src/client/containers/ConfirmationPage/ConfirmationPage.Style.css
Labels: Frontend

#217 Frontend: button to go home in Monthly Arrivals Page
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
Labels: Frontend

#212 add ShoppingCart context
  src/client/AppContainer.js
  src/client/containers/ProductPage/ProductPage.Container.js
  src/client/context/shoppingCart/ShoppingCartProvider.js
  src/client/context/shoppingCart/index.js
  src/client/context/shoppingCart/shoppingCartContext.js
Labels: Frontend

#208 Payment: adding Paypal component
  public/index.html
  src/client/.storybook/preview-head.html
  src/client/components/Paypal/Paypal.component.js
  src/client/components/Paypal/Paypal.stories.js
Labels: storybook, Frontend, Backend

#219 FrontEnd: Contact page change according to design
  src/client/assets/images/Phone_icon.png
  src/client/assets/images/clock-icon.png
  src/client/assets/images/contact-us.png
  src/client/assets/images/email-icon.png
  src/client/assets/images/location-icon.png
  src/client/containers/ContactPage/ContactPage.Container.js
  src/client/containers/ContactPage/ContactPage.Style.css
Labels: Frontend

#220 FrontEnd: Modal comes when add to cart click
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/ShoppingItem/ShoppingItem.styles.css
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
Labels: Frontend

#224 BackEnd: Files added to Production same as Development
  src/server/seeds/development/02_products.js
  src/server/seeds/production/02_products.js
  src/server/seeds/production/03_users.js
  src/server/seeds/production/04_favorites.js
  src/server/seeds/production/05_orders.js
Labels: Backend

#237 FrontEnd: Favorite icon function Monthly Page and Product Page - adding product to favorites
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/menu/Menu.component.js
  src/client/containers/LandingPage/LandingPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#225 adding auth, showing user or guest
  src/client/App.js
  src/client/containers/CartPage/CartPage.Container.js
Labels: Frontend

#229 fixing shopping cart image loading on heroku
  src/client/components/ShoppingItem/ShoppingItem.js
Labels: Frontend

#241 Frontend: Small fix modal css
  src/client/components/Modal/Modal.styles.css
Labels: Frontend

#240 FrontEnd: bug fixed for guest productpage
  src/client/App.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#238 Frontend: Delivery info styles and order page styles
  src/client/components/DeliveryInfo/DeliveryInfo.styles.css
  src/client/components/Purchases/Purchases.styles.css
  src/client/containers/OrderPage/OrderPage.Container.js
  src/client/containers/OrderPage/OrderPage.Style.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
  src/client/containers/ProfilePage/ProfilePage.Style.css
Labels: Frontend

#248 Backend: Bug on getting duplicate favorites which displaying on Favorites Page
  src/client/App.js
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/menu/Menu.component.js
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/server/api/controllers/users.controller.js
Labels: Backend

#250 FrontEnd: Update For Product Details CSS
  src/client/components/ProductDetails/ProductDetails.style.css
Labels: Frontend

#245 Cart using shopping context (localStorage)
  src/client/App.js
  src/client/components/ShoppingItem/ShoppingItem.js
  src/client/containers/CartPage/CartPage.Container.js
Labels: Frontend

#255 Fix Css in TotalPrice and order page to display order page according to figma
  src/client/components/TotalPriceCard/TotalPriceCard.component.js
  src/client/components/TotalPriceCard/TotalPriceCard.styles.css
  src/client/containers/OrderPage/OrderPage.Style.css
Labels: enhancement, Frontend

#260 FrontEnd: Class Names in front of every component and Container
  src/client/components/Button/Button.styles.css
  src/client/components/ButtonV2/ButtonV2.component.js
  src/client/components/ButtonV2/ButtonV2.stories.js
  src/client/components/Carousel/Carousel.style.css
  src/client/components/ContactForm/ContactForm.styles.css
  src/client/components/HeroImage/HeroImage.styles.css
  src/client/components/Loader/Loader.styles.css
  src/client/components/ProductView/ProductView.styles.css
  src/client/components/ShoppingItem/ShoppingItem.styles.css
  src/client/components/Sorting/Sorting.styles.css
  src/client/components/TotalPriceCard/TotalPriceCard.styles.css
  src/client/components/menu/Menu.styles.css
  src/client/containers/404Page/404Page.Container.js
  src/client/containers/404Page/404Page.Style.css
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/CartPage/CartPage.Style.css
  src/client/containers/CategoryPage/CategoryPage.Style.css
  src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
  src/client/containers/ConfirmationPage/ConfirmationPage.Style.css
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/FavoritesPage/FavoritesPage.Style.css
  src/client/containers/LandingPage/LandingPage.Container.js
  src/client/containers/LandingPage/LandingPage.Style.css
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Style.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
  src/client/containers/ProfilePage/ProfilePage.Style.css
Labels: Frontend

#251 guest user and logged in user handling on cart page
  src/client/.storybook/preview.js
  src/client/components/ButtonV2/ButtonV2.stories.js
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/ProductDetails/ProductDetails.stories.js
  src/client/components/ShoppingItem/ShoppingItem.js
  src/client/components/ShoppingItem/ShoppingItem.stories.js
  src/client/components/TotalPriceCard/TotalPriceCard.component.js
  src/client/components/TotalPriceCard/TotalPriceCard.styles.css
  src/client/components/menu/Menu.component.js
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/CartPage/CartPage.Style.css
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/OrderPage/OrderPage.Style.css
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: Frontend

#244 Backend: Update stock amount
  src/server/api/controllers/products.controller.js
  src/server/api/routes/products.router.js
Labels: Backend

#249 Implemented badge on Cart Icon to display the number of items added to the Cart
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.styles.css
Labels: Frontend

#265 Add functionalities to the Shopping Cart Page Buttons (REVIEW ORDER & KEEP SHOPPING)
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/OrderPage/OrderPage.Container.js
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/orders.router.js
Labels: Frontend, Backend

#267 Frontend: Login/logout redirection to landing page
  src/client/components/menu/Menu.component.js
Labels: Frontend

#258 Bug FrontEnd: Bugs on mobile menu And Favorites Authorization
  src/client/App.js
  src/client/components/menu/Menu.component.js
  src/client/containers/FavoritesPage/FavoritesPage.Container.js
  src/client/containers/FavoritesPage/FavoritesPage.Style.css
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
Labels: Frontend

#269 Added clear shopping Cart from local storage on logout
  src/client/components/menu/Menu.component.js
  src/client/context/shoppingCart/ShoppingCartProvider.js
Labels: Frontend

#266 Frontend: Added payment button and redirect to order confirmation
  public/index.html
  src/client/App.js
  src/client/components/Paypal/Paypal.component.js
  src/client/containers/CartPage/CartPage.Container.js
  src/client/containers/ConfirmationPage/ConfirmationPage.Container.js
  src/client/containers/OrderPage/OrderPage.Container.js
  src/server/api/controllers/orders.controller.js
  src/server/api/routes/orders.router.js
Labels: Frontend

#264 Frontend: Shopping Cart and Order Page Responsive Design
  src/client/components/ContactForm/ContactForm.styles.css
  src/client/components/ShoppingItem/ShoppingItem.styles.css
  src/client/components/TotalPriceCard/TotalPriceCard.component.js
  src/client/components/TotalPriceCard/TotalPriceCard.styles.css
  src/client/containers/CartPage/CartPage.Style.css
  src/client/containers/OrderPage/OrderPage.Style.css
  src/client/containers/ProfilePage/ProfilePage.Style.css
Labels: Frontend

#281 Frontend: Profile page styles and responsive
  src/client/components/Purchases/Purchases.styles.css
  src/client/containers/ProfilePage/ProfilePage.Style.css
Labels: Frontend

#284 Frontend: Change color based on the site theme & fill color on entire field for Category option on SortBy
  src/client/components/Sorting/Sorting.styles.css
Labels: Frontend

#286 Fixed the current bug on unit price of cart page
  src/client/components/ShoppingItem/ShoppingItem.js
Labels: Frontend

#277 FrontEnd: Make the Menu bar sticky so when we scroll down we can always access it
  src/client/components/Carousel/Carousel.style.css
  src/client/components/ProductDetails/ProductDetails.style.css
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.styles.css
Labels: Frontend

#295 FrontEnd: CLEAN code that we are not using (components)
  src/client/App.js
  src/client/components/Forms/Forms.stories.js
  src/client/components/Forms/ResetPassword.js
  src/client/components/Forms/SignIn.js
  src/client/components/Forms/SignUp.js
  src/client/containers/ResetPassword/ResetPassword.stories.js
  src/client/containers/ResetPassword/index.js
  src/client/containers/SignIn/index.js
  src/client/containers/SignUp/index.js
Labels: Frontend

#296 Frontend/improvement: Change the background color of the pagination buttons to the web app theme color: violet
  src/client/components/ProductsPagination/ProductsPagination.styles.css
Labels: Frontend

#290 Frontend: Update stock amount
  src/client/components/Button/Button.styles.css
  src/client/containers/OrderPage/OrderPage.Container.js
  src/server/api/controllers/products.controller.js
Labels: Frontend

#298 Frontend: Fix stock amount for already added Zero value
  src/server/api/controllers/products.controller.js
Labels: Frontend

#275 Bug: Not showing the orders on my profile page once I finish the payment
  src/client/components/Purchases/Purchases.component.js
  src/client/components/Purchases/Purchases.stories.js
  src/client/components/Purchases/Purchases.styles.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
Labels: bug, Frontend

#300 Revert "Bug: Not showing the orders on my profile page once I finish the payment"
  src/client/components/Purchases/Purchases.component.js
  src/client/components/Purchases/Purchases.stories.js
  src/client/components/Purchases/Purchases.styles.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
Labels: bug

#302 Revert "Revert "Bug: Not showing the orders on my profile page once I…
  src/client/components/Purchases/Purchases.component.js
  src/client/components/Purchases/Purchases.stories.js
  src/client/components/Purchases/Purchases.styles.css
  src/client/containers/ProfilePage/ProfilePage.Container.js
Labels: bug

#301 Bug: Not showing the orders on my profile page once I finish the payment
  src/client/containers/CartPage/CartPage.Container.js
  src/server/api/controllers/orders.controller.js
Labels: bug

#282 FrontEnd/Bug: Home button on Menu And Go Home button Bug
  src/client/assets/images/home.png
  src/client/components/DeliveryInfo/DeliveryInfoV2.component.js
  src/client/components/ProductDetails/ProductDetails.component.js
  src/client/components/menu/Menu.component.js
  src/client/components/menu/Menu.styles.css
  src/client/containers/CategoryPage/CategoryPage.Container.js
  src/client/containers/MonthlyArrivalsPage/MonthlyArrivalsPage.Container.js
  src/client/containers/ProductPage/ProductPage.Container.js
Labels: bug, Frontend

#288 FrontEnd: Any image click to product in Favorites and Monthly Arrival Page
  src/client/components/ProductDetails/ProductDetails.component.js
Labels: Frontend

#297 Frontend: Alert message before Review
  src/client/components/Modal/Modal.styles.css
  src/client/components/Modal/Modal2.component.js
  src/client/containers/CartPage/CartPage.Container.js
Labels: Frontend

#303 Deployment: Compare and merging develop branch to master branch
  README.md
Labels: Deployment

#306 Bug/FrontEnd: Fix scroll to top instead of staying where you stopped on previous page
  src/client/App.js
  src/client/ScrollToTop.js
Labels: bug
